name: Test and Build Anchor

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.5.0'  # Use Node.js version 23.5.0
          cache: 'npm'  # Cache npm dependencies

      - name: Install dependencies with npm
        run: npm install --legacy-peer-deps  # Use npm to install dependencies

      - uses: metadaoproject/setup-anchor@v2
        with:
          anchor-version: '0.30.1'
          node-version: '23.5.0'
          solana-cli-version: '1.18.9'

      - name: Generate new keypair
        run: solana-keygen new --no-bip39-passphrase

      - name: Set solana target cluster to local
        run: solana config set --url http://localhost:8899

      - name: Check solana config
        run: solana config get

      - run: npm run anchor build  # Use npm to run build
        shell: bash

      - run: npm run anchor test  # Use npm to run tests
        shell: bash


      - run: pnpm run anchor test
        shell: bash
